### ISSUE TITLE
Add validation for supported raid types

### ISSUE THREAD

**Issue by shovanmaity** [mayadata-io/cstorpoolauto#102]
While provisioning a CStor Pool using local block devices if I passed a wrong raid type then it experiences panic.

log
```bash
mayadata.io/cstorpoolauto/unstruct.GetString
	/mayadata.io/cstorpoolauto/unstruct/util.go:97
mayadata.io/cstorpoolauto/unstruct.GetStringOrError
	/mayadata.io/cstorpoolauto/unstruct/util.go:69
mayadata.io/cstorpoolauto/util/cstorclusterconfig.(*Helper).GetRAIDType
	/mayadata.io/cstorpoolauto/util/cstorclusterconfig/helper.go:128
mayadata.io/cstorpoolauto/util/cstorclusterconfig.(*Helper).GetRAIDTypeOrCached
	/mayadata.io/cstorpoolauto/util/cstorclusterconfig/helper.go:147
mayadata.io/cstorpoolauto/controller/localdevice.(*Reconciler).setRAIDType
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:274
mayadata.io/cstorpoolauto/controller/localdevice.(*Reconciler).Reconcile
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:387
mayadata.io/cstorpoolauto/controller/localdevice.(*syncer).reconcile
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:133
mayadata.io/cstorpoolauto/controller/localdevice.(*syncer).sync
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:194
mayadata.io/cstorpoolauto/controller/localdevice.Sync
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:231
openebs.io/metac/controller/generic.(*InlineHookInvoker).Invoke
```

**Comment by AmitKumarDas** [comment]
```
0317 08:49:24.144943       1 reconciler.go:91] Started LocalDevice sync: Watch "CStorClusterConfig" - "openebs" / "stripe-1"
I0317 08:49:24.145732       1 controller.go:438] WatchGCtl cspauto/sync-config-local: Watch dao.mayadata.io/v1alpha1:CStorClusterConfig:openebs:stripe-1 sync completed
E0317 08:49:24.145915       1 runtime.go:78] Observed a panic: "integer divide by zero" (runtime error: integer divide by zero)
goroutine 269 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x12fed60, 0x201e0b0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x12fed60, 0x201e0b0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
mayadata.io/cstorpoolauto/util/cstorclusterconfig.(*Helper).IsDiskCountMatchRAIDType(0xc0003b5ad0, 0x1, 0xc000232fe8, 0x12a5aa0, 0x0)
	/mayadata.io/cstorpoolauto/util/cstorclusterconfig/helper.go:115 +0x1c5
mayadata.io/cstorpoolauto/controller/localdevice.(*Reconciler).isSelectedBlockDeviceCountMatchRAIDType(0xc0002d2c30)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:305 +0xdf
mayadata.io/cstorpoolauto/controller/localdevice.(*Reconciler).Reconcile(0xc0002d2c30, 0xc0002d2c30, 0xc000575830, 0xc00078d230, 0x1, 0x1, 0xc0006cb320)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:387 +0x1ac
mayadata.io/cstorpoolauto/controller/localdevice.(*syncer).reconcile(0xc000102c60)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:133 +0xa9
mayadata.io/cstorpoolauto/controller/localdevice.(*syncer).sync(0xc000102c60, 0xc000102c60, 0x37)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:194 +0x17f
mayadata.io/cstorpoolauto/controller/localdevice.Sync(0xc000414ac0, 0xc000212580, 0xc000505030, 0x10)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:231 +0x59
openebs.io/metac/controller/generic.(*InlineHookInvoker).Invoke(0xc00078d408, 0xc000414ac0, 0xc000212580, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/inlinehook.go:68 +0x7c
openebs.io/metac/controller/generic.(*HookInvoker).Invoke(0xc00078d470, 0xc000414ac0, 0xc000212580, 0x16, 0xc00078d498)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/hooks.go:92 +0x9f
openebs.io/metac/controller/generic.(*watchController).callSyncHook(0xc000138a80, 0xc000414ac0, 0xc0003b50b0, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:878 +0x1bc
openebs.io/metac/controller/generic.(*watchController).syncWatchObj(0xc000138a80, 0xc00010a268, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:539 +0x3c9
openebs.io/metac/controller/generic.(*watchController).syncWatch(0xc000138a80, 0xc000476d80, 0x3c, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:469 +0x386
openebs.io/metac/controller/generic.(*watchController).processNextWorkItem(0xc000138a80, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:350 +0x103
openebs.io/metac/controller/generic.(*watchController).worker(0xc000138a80)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:327 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003e8fb0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000233fb0, 0x3b9aca00, 0x0, 0x30100000001, 0xc00046a1e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88
openebs.io/metac/controller/generic.(*watchController).Start.func1.1(0xc000055750, 0xc000138a80)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:289 +0xa3
created by openebs.io/metac/controller/generic.(*watchController).Start.func1
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:287 +0x7ec
panic: runtime error: integer divide by zero [recovered]
	panic: runtime error: integer divide by zero
goroutine 269 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x12fed60, 0x201e0b0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
mayadata.io/cstorpoolauto/util/cstorclusterconfig.(*Helper).IsDiskCountMatchRAIDType(0xc0003b5ad0, 0x1, 0xc000232fe8, 0x12a5aa0, 0x0)
	/mayadata.io/cstorpoolauto/util/cstorclusterconfig/helper.go:115 +0x1c5
mayadata.io/cstorpoolauto/controller/localdevice.(*Reconciler).isSelectedBlockDeviceCountMatchRAIDType(0xc0002d2c30)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:305 +0xdf
mayadata.io/cstorpoolauto/controller/localdevice.(*Reconciler).Reconcile(0xc0002d2c30, 0xc0002d2c30, 0xc000575830, 0xc00078d230, 0x1, 0x1, 0xc0006cb320)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:387 +0x1ac
mayadata.io/cstorpoolauto/controller/localdevice.(*syncer).reconcile(0xc000102c60)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:133 +0xa9
mayadata.io/cstorpoolauto/controller/localdevice.(*syncer).sync(0xc000102c60, 0xc000102c60, 0x37)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:194 +0x17f
mayadata.io/cstorpoolauto/controller/localdevice.Sync(0xc000414ac0, 0xc000212580, 0xc000505030, 0x10)
	/mayadata.io/cstorpoolauto/controller/localdevice/reconciler.go:231 +0x59
openebs.io/metac/controller/generic.(*InlineHookInvoker).Invoke(0xc00078d408, 0xc000414ac0, 0xc000212580, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/inlinehook.go:68 +0x7c
openebs.io/metac/controller/generic.(*HookInvoker).Invoke(0xc00078d470, 0xc000414ac0, 0xc000212580, 0x16, 0xc00078d498)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/hooks.go:92 +0x9f
openebs.io/metac/controller/generic.(*watchController).callSyncHook(0xc000138a80, 0xc000414ac0, 0xc0003b50b0, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:878 +0x1bc
openebs.io/metac/controller/generic.(*watchController).syncWatchObj(0xc000138a80, 0xc00010a268, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:539 +0x3c9
openebs.io/metac/controller/generic.(*watchController).syncWatch(0xc000138a80, 0xc000476d80, 0x3c, 0x0, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:469 +0x386
openebs.io/metac/controller/generic.(*watchController).processNextWorkItem(0xc000138a80, 0x0)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:350 +0x103
openebs.io/metac/controller/generic.(*watchController).worker(0xc000138a80)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:327 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003e8fb0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000233fb0, 0x3b9aca00, 0x0, 0x30100000001, 0xc00046a1e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88
openebs.io/metac/controller/generic.(*watchController).Start.func1.1(0xc000055750, 0xc000138a80)
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:289 +0xa3
created by openebs.io/metac/controller/generic.(*watchController).Start.func1
	/go/pkg/mod/github.com/!amit!kumar!das/metac@v0.1.1-0.20200207112147-5bfc4b3f4af9/controller/generic/controller.go:287 +0x7ec
```

**Comment by AmitKumarDas** [comment]
PR #107
